### ISSUE TITLE
Random Ping request made from server to client

### ISSUE THREAD

**Issue by shyzus** [ThorbenKuck/NetCom2#101] opened 2018-05-19 23:04 UTC
## Setup

    I am using NetCom2 1.0.1
    Using JDK 10, experienced this issue before on JDK 1.8
    Discovered this bug in IDE and in packaged jars using maven goal: compile assemble:single
    No firewall applicable experiencing while running client and server on localhost and in LAN
    Using Windows 10 when using localhost. When using LAN using Raspberry Pi Debian 9 as server and Windows 10 as client
    
## Description
    
 The problem I am experiencing is simple, at random times when launching the client to connect to the server even before anything is done such as loading the FX Application Thread. (I use JavaFX for my application) I get the following error and the client needs to be restarted to work again:

com.github.thorbenkuck.netcom2.exceptions.CommunicationNotSpecifiedException: Nothing registered for class com.github.thorbenkuck.netcom2.network.shared.comm.model.Ping
	at com.github.thorbenkuck.netcom2.network.shared.comm.DefaultCommunicationRegistration.handleNotRegistered(DefaultCommunicationRegistration.java:69)
	at com.github.thorbenkuck.netcom2.network.shared.comm.DefaultCommunicationRegistration.trigger(DefaultCommunicationRegistration.java:223)
	at com.github.thorbenkuck.netcom2.network.shared.clients.DefaultReceivingService.trigger(DefaultReceivingService.java:157)
	at com.github.thorbenkuck.netcom2.network.shared.clients.DefaultReceivingService.handle(DefaultReceivingService.java:88)
	at com.github.thorbenkuck.netcom2.network.shared.clients.DefaultReceivingService.lambda$run$4(DefaultReceivingService.java:234)
	at com.github.thorbenkuck.netcom2.utility.NetCom2Utils.runOnNetComThread(NetCom2Utils.java:327)
	at com.github.thorbenkuck.netcom2.network.shared.clients.DefaultReceivingService.run(DefaultReceivingService.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
	at com.github.thorbenkuck.netcom2.utility.NetComThread.run(NetComThread.java:94)
## Steps
    
1. Create a basic application that implements NetCom2 1.0.1 
2. Attempt to launch the client
3. See it print the above or error or try step 2 again.

**Comment by ThorbenKuck** [comment] 2018-05-20 06:32
Interresting.. I cannot replicate this Issue, but i can see the Problem in code.

Inside the ClientStartImpl the sequence of actions should be the following:
register internals, connect, synchronize (await Ping).

But the register internals ich done after the connect. This bug was changed in a previous commit, but appears to be un done .. 

In my oppinion, this is urgend, since the behaviour is unpredictable. Oppinions?

**Comment by ThorbenKuck** [comment] 2018-05-20 06:55
The fix will be fixed, pushed, and released today.

**Comment by ThorbenKuck** [comment] 2018-05-20 07:18
I added a Pull-Request. Do you have any way of verifing, that this works with this potential fix (checking out the branch #101_Random_Ping_Bug and testing it or something like this)? I want to be sure before releasing a potential fix.

**Comment by shyzus** [comment] 2018-05-20 10:57
I should be able to manually clone branch #101_Random_Ping_Bug. Temporarily remove the maven depency from my pom.xml and add the folder as a library in IntelliJ IDEA and run it for 50 times or so and see if it fails or not.

**Comment by ThorbenKuck** [comment] 2018-05-20 11:02
Sure, go ahead! On my machine this error is not reproducable.
If you don't know: Under src/test/java/com.github.thorbenkuck.integration are a handfull of tests that test stuff that is no where near a unit test. The Server and Client Class should be good.

**Comment by shyzus** [comment] 2018-05-20 11:46
I have launched a server instance and relaunched a client repeatedly for atleast 50 runs, no errors came up. I ran the unit tests of the NetCom2 1.0.2, no failures were found. So far it looks pretty good, good job on that. However I was unable to run the integration tests you mentioned. I am not too familiar with running those kind of tests.

**Comment by ThorbenKuck** [comment] 2018-05-20 11:49
Okay. Than i am going to approve the merge and would like to perfom a push-up-update from dev to master, release 1.0.2 and perform a pull-down-update. Any oppositions?

They have a main method, that you can execute. Technically speaking: those are simple small test-applications.

**Comment by ThorbenKuck** [comment] 2018-05-20 11:50
Fixed. Therefor closed.

**Closed by ThorbenKuck** 2018-05-20 11:50 UTC
Labels: bug, urgent

**Comment by shyzus** [comment] 2018-05-20 11:53
On the topic of integration test I do know how to launch them via the main method, however the server.main() method does run but has no output for quite sometime, unsure if something is going wrong here or that its supposed to take a bit before some output

**Comment by ThorbenKuck** [comment] 2018-05-20 12:06
Interresting. The Server class should have no output. The only output that should happen is, if error occoured. Done correctly, the Server should have no Output, except if you change the NetComLogging of course
